name: wbdsjunior-taponphone
services:
  wbdsjunior-taponphone-markets:
    depends_on:
      wbdsjunior-taponphone-markets-postgres:
        condition: service_healthy
    image: wbdsjunior-taponphone-markets
    build:
      context: ./taponphone-markets
      dockerfile: ./Dockerfile
      no_cache: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wbdsjunior-taponphone-markets-postgres:5432/taponphone-markets
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_FEIGNCLIENT_TAPONPHONE_PAYMENTS_SERVICE_URL=http://wbdsjunior-taponphone-payments:8082
    ports:
      - 8081:8081
    networks:
      - wbdsjunior-taponphone
    healthcheck:
      test: curl --fail --silent http://localhost:8081/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  wbdsjunior-taponphone-markets-postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=taponphone-markets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - wbdsjunior-taponphone-markets-postgres:/var/lib/postgresql
    networks:
      - wbdsjunior-taponphone
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
  wbdsjunior-taponphone-payments:
    depends_on:
      wbdsjunior-taponphone-payments-mongo:
        condition: service_healthy
    image: wbdsjunior-taponphone-payments
    build:
      context: ./taponphone-payments
      dockerfile: ./Dockerfile
      no_cache: true
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://wbdsjunior-taponphone-payments-mongo:27017/taponphone-payments
    ports:
      - 8082:8082
    networks:
      - wbdsjunior-taponphone
    healthcheck:
      test: curl --fail --silent http://localhost:8082/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  wbdsjunior-taponphone-payments-mongo:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - wbdsjunior-taponphone-payments-mongo:/data/db
    networks:
      - wbdsjunior-taponphone
    healthcheck:
      test: echo 'db.stats().ok' | mongosh test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  wbdsjunior-taponphone-markets-postgres:
  wbdsjunior-taponphone-payments-mongo:
networks:
  wbdsjunior-taponphone:
