version: '2.4'
name: wbdsjunior-taponphone
networks:
  wbdsjunior-taponphone:
volumes:
  wbdsjunior-taponphone-api-gateway-redis:
  wbdsjunior-taponphone-authentications-postgres:
  wbdsjunior-taponphone-markets-postgres:
  wbdsjunior-taponphone-payments-mongo:
services:
  wbdsjunior-taponphone-api-gateway:
    build:
      context: ./taponphone-api-gateway
      no_cache: true
    image: wbdsjunior-taponphone-api-gateway:1
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_DISTRIBUTED_TRACING_ZIPKIN_ENDPONT=http://wbdsjunior-taponphone-zipkin:9411/api/v2/spans
      - SPRING_DATA_REDIS_URL=redis://wbdsjunior-taponphone-api-gateway-redis:6379/0
      - SPRING_GATEWAY_TAPONPHONE_AUTHENTICATIONS_SERVICE_URI=http://wbdsjunior-taponphone-authentications:8080
      - SPRING_GATEWAY_TAPONPHONE_MARKETS_SERVICE_URI=http://wbdsjunior-taponphone-markets:8080
      - SPRING_GATEWAY_TAPONPHONE_PAYMETS_SERVICE_URI=http://wbdsjunior-taponphone-payments:8080
    networks:
      - wbdsjunior-taponphone
    ports:
      - 8080:8080
    depends_on:
      wbdsjunior-taponphone-zipkin:
        condition: service_healthy
      wbdsjunior-taponphone-api-gateway-redis:
        condition: service_healthy
    healthcheck:
      test: wget http://localhost:8080/actuator/health/readiness -O - | grep UP || exit 1
  wbdsjunior-taponphone-api-gateway-redis:
    image: redis:7-alpine
    environment:
      - TZ=America/Sao_Paulo
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - wbdsjunior-taponphone
    volumes:
      - wbdsjunior-taponphone-api-gateway-redis:/data
    healthcheck:
      test: redis-cli ping | grep PONG || exit 1
    restart: always
  wbdsjunior-taponphone-authentications:
    build:
      context: ./taponphone-authentications
      no_cache: true
    image: wbdsjunior-taponphone-authentications:1
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_DISTRIBUTED_TRACING_ZIPKIN_ENDPONT=http://wbdsjunior-taponphone-zipkin:9411/api/v2/spans
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wbdsjunior-taponphone-authentications-postgres:5432/taponphone-authentications?user=postgres&password=postgres
    networks:
      - wbdsjunior-taponphone
    depends_on:
      wbdsjunior-taponphone-zipkin:
        condition: service_healthy
      wbdsjunior-taponphone-authentications-postgres:
        condition: service_healthy
    healthcheck:
      test: wget http://localhost:8080/actuator/health/readiness -O - | grep UP || exit 1
  wbdsjunior-taponphone-authentications-postgres:
    image: postgres:16-alpine
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taponphone-authentications
    networks:
      - wbdsjunior-taponphone
    volumes:
      - wbdsjunior-taponphone-authentications-postgres:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U postgres
    restart: always
  wbdsjunior-taponphone-markets:
    build:
      context: ./taponphone-markets
      no_cache: true
    image: wbdsjunior-taponphone-markets:1
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_DISTRIBUTED_TRACING_ZIPKIN_ENDPONT=http://wbdsjunior-taponphone-zipkin:9411/api/v2/spans
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wbdsjunior-taponphone-markets-postgres:5432/taponphone-markets?user=postgres&password=postgres
      - SPRING_FEIGNCLIENT_TAPONPHONE_PAYMENTS_SERVICE_URL=http://wbdsjunior-taponphone-payments:8080
    networks:
      - wbdsjunior-taponphone
    depends_on:
      wbdsjunior-taponphone-zipkin:
        condition: service_healthy
      wbdsjunior-taponphone-markets-postgres:
        condition: service_healthy
    healthcheck:
      test: wget http://localhost:8080/actuator/health/readiness -O - | grep UP || exit 1
  wbdsjunior-taponphone-markets-postgres:
    image: postgres:16-alpine
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taponphone-markets
    networks:
      - wbdsjunior-taponphone
    volumes:
      - wbdsjunior-taponphone-markets-postgres:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U postgres
    restart: always
  wbdsjunior-taponphone-payments:
    build:
      context: ./taponphone-payments
      no_cache: true
    image: wbdsjunior-taponphone-payments:1
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_DISTRIBUTED_TRACING_ZIPKIN_ENDPONT=http://wbdsjunior-taponphone-zipkin:9411/api/v2/spans
      - SPRING_DATA_MONGODB_URI=mongodb://wbdsjunior-taponphone-payments-mongo:27017/taponphone-payments
    networks:
      - wbdsjunior-taponphone
    depends_on:
      wbdsjunior-taponphone-zipkin:
        condition: service_healthy
      wbdsjunior-taponphone-payments-mongo:
        condition: service_healthy
    healthcheck:
      test: wget http://localhost:8080/actuator/health/readiness -O - | grep UP || exit 1
  wbdsjunior-taponphone-payments-mongo:
    image: mongo:7
    environment:
      - TZ=America/Sao_Paulo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    networks:
      - wbdsjunior-taponphone
    volumes:
      - wbdsjunior-taponphone-payments-mongo:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongosh -u mongo -p mongo --authenticationDatabase admin test --quiet
    restart: always
  wbdsjunior-taponphone-zipkin:
    image: openzipkin/zipkin:2
    environment:
      - TZ=America/Sao_Paulo
      - STORAGE_TYPE=mem
    networks:
      - wbdsjunior-taponphone
    ports:
      - 9411:9411
    healthcheck:
      test: wget http://localhost:9411/health -O - | sed ':a;N;$!ba;s/\s//g' | grep 'zipkin":{"status":"UP' || exit 1