name: taponphone-authentications
networks:
  taponphone-authentications:
volumes:
  taponphone-authentications-postgres:
services:
  taponphone-authentications:
    extends:
      file: ./docker-compose.base.yaml
      service: base
    build:
      dockerfile: ./Dockerfile
      no_cache: true
    image: taponphone-authentications:1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://taponphone-authentications-postgres:5432/taponphone-authentications?user=postgres&password=postgres
    ports:
      - 8080:8080
    depends_on:
      taponphone-authentications-postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent http://localhost:8080/actuator/health/readiness | grep UP || exit 1
  taponphone-authentications-postgres:
    extends:
      file: ./docker-compose.base.yaml
      service: base
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taponphone-authentications
    volumes:
      - taponphone-authentications-postgres:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U postgres
    restart: always
