name: markets
networks:
  markets:
volumes:
  markets-postgres:
services:
  markets-postgres:
    extends:
      file: ./compose.base.yaml
      service: base
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taponphone-markets
    volumes:
      - markets-postgres:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U postgres
    restart: always
