version: '3.4'
services:
  taponphone-markets:
    depends_on:
      taponphone-markets-postgres:
        condition: service_healthy
    image: taponphone-markets
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    networks:
      - taponphone-markets
    healthcheck:
      test: curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  taponphone-markets-postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=taponphone-markets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - taponphone-markets-postgres:/var/lib/postgresql
    networks:
      - taponphone-markets
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  taponphone-markets-postgres:
networks:
  taponphone-markets:
