name: taponphone-markets
services:
  taponphone-markets:
    depends_on:
      taponphone-markets-postgres:
        condition: service_healthy
    image: taponphone-markets
    build:
      context: .
      dockerfile: ./Dockerfile
      no_cache: true
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=50051,quiet=y
      - SPRING_DATASOURCE_URL=jdbc:postgresql://taponphone-markets-postgres:5432/taponphone-markets
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_FEIGNCLIENT_TAPONPHONE_PAYMENTS_SERVICE_URL=http://taponphone-payments:8082
    ports:
      - 8081:8081
      - 50051:50051
    networks:
      - taponphone-markets
    healthcheck:
      test: curl --fail --silent http://localhost:8081/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  taponphone-markets-postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=taponphone-markets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - taponphone-markets-postgres:/var/lib/postgresql
    networks:
      - taponphone-markets
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  taponphone-markets-postgres:
networks:
  taponphone-markets:
