name: payments
networks:
  payments:
volumes:
  payments-mongo:
services:
  payments-mongo:
    extends:
      file: ./compose.base.yaml
      service: base
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - payments-mongo:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.stats().ok' | mongosh -u mongo -p mongo --authenticationDatabase admin test --quiet
    restart: always
