name: payments
services:
  payments-mongo:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - payments-mongo:/data/db
    networks:
      - payments
    healthcheck:
      test: echo 'db.stats().ok' | mongosh test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  payments-mongo:
networks:
  payments:
