version: '3.4'
services:
  mongo:
    image: mongo:6
    environment:
      - MONGO_INITDB_DATABASE=taponphone-payments
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
volumes:
  mongo:
