version: '2.4'
name: taponphone-payments
networks:
  taponphone-payments:
volumes:
  taponphone-payments-mongo:
services:
  taponphone-payments:
    build:
      context: .
      no_cache: true
    image: taponphone-payments:1
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_DISTRIBUTED_TRACING_ZIPKIN_ENDPONT=http://taponphone-payments-zipkin:9411/api/v2/spans
      - SPRING_DATA_MONGODB_URI=mongodb://taponphone-payments-mongo:27017/taponphone-payments
    networks:
      - taponphone-payments
    ports:
      - 8080:8080
    depends_on:
      taponphone-payments-zipkin:
        condition: service_healthy
      taponphone-payments-mongo:
        condition: service_healthy
    healthcheck:
      test: wget http://localhost:8080/actuator/health/readiness -O - | grep UP || exit 1
  taponphone-payments-zipkin:
    image: openzipkin/zipkin:2
    environment:
      - TZ=America/Sao_Paulo
      - STORAGE_TYPE=mem
    networks:
      - taponphone-payments
    ports:
      - 9411:9411
    healthcheck:
      test: wget http://localhost:9411/health -O - | sed ':a;N;$!ba;s/\s//g' | grep 'zipkin":{"status":"UP' || exit 1
  taponphone-payments-mongo:
    image: mongo:7
    environment:
      - TZ=America/Sao_Paulo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    networks:
      - taponphone-payments
    volumes:
      - taponphone-payments-mongo:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongosh -u mongo -p mongo --authenticationDatabase admin test --quiet
    restart: always
