version: '2.4'
name: payments
networks:
  payments:
volumes:
  mongo:
services:
  payments:
    labels:
      org.springframework.boot.ignore: true
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000,quiet=y
      no_cache: true
    image: payments:snapshot
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_DISTRIBUTED_TRACING_ZIPKIN_ENDPONT=http://zipkin:9411/api/v2/spans
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/payments
    networks:
      - payments
    ports:
      - 8000:8000
      - 8080:8080
    volumes:
      - .:/home/java/work
    depends_on:
      zipkin:
        condition: service_healthy
      mongo:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent http://localhost:8080/actuator/health/readiness | grep UP || exit 1
  zipkin:
    image: openzipkin/zipkin:2
    environment:
      - TZ=America/Sao_Paulo
      - STORAGE_TYPE=mem
    networks:
      - payments
    ports:
      - 9411:9411
    healthcheck:
      test: wget http://localhost:9411/health -O - | sed ':a;N;$!ba;s/\s//g' | grep 'zipkin":{"status":"UP' || exit 1
  mongo:
    image: mongo:7
    environment:
      - TZ=America/Sao_Paulo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    networks:
      - payments
    volumes:
      - mongo:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongosh -u mongo -p mongo --authenticationDatabase admin test --quiet
    restart: always
