name: taponphone-payments
services:
  taponphone-payments:
    depends_on:
      taponphone-payments-mongo:
        condition: service_healthy
    image: taponphone-payments
    build:
      context: .
      dockerfile: ./Dockerfile
      no_cache: true
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://taponphone-payments-mongo:27017/taponphone-payments
    ports:
      - 8082:8082
    networks:
      - taponphone-payments
    healthcheck:
      test: curl --fail --silent http://localhost:8082/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  taponphone-payments-mongo:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - taponphone-payments-mongo:/data/db
    networks:
      - taponphone-payments
    healthcheck:
      test: echo 'db.stats().ok' | mongosh test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  taponphone-payments-mongo:
networks:
  taponphone-payments:
