name: taponphone-payments
networks:
  taponphone-payments:
volumes:
  taponphone-payments-mongo:
services:
  taponphone-payments:
    extends:
      file: ./docker-compose.base.yaml
      service: base
    build:
      dockerfile: ./Dockerfile
      no_cache: true
    image: taponphone-payments:1
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000,quiet=y
      - SPRING_DATA_MONGODB_URI=mongodb://taponphone-payments-mongo:27017/taponphone-payments
    ports:
      - 8000:8000
      - 8080:8080
    depends_on:
      taponphone-payments-mongo:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent http://localhost:8080/actuator/health/readiness | grep UP || exit 1
  taponphone-payments-mongo:
    extends:
      file: ./docker-compose.base.yaml
      service: base
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - taponphone-payments-mongo:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongosh -u mongo -p mongo --authenticationDatabase admin test --quiet
    restart: always
