name: api-gateway
networks:
  api-gateway:
volumes:
  api-gateway-redis:
services:
  redis:
    extends:
      file: ./compose.base.yaml
      service: base
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - api-gateway-redis:/data
    healthcheck:
      test: redis-cli ping | grep PONG || exit 1
    restart: always
