management:
  defaults:
    metrics:
      export:
        enabled: false
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  error:
    whitelabel:
      enabled: false
  port: 8082

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/taponphone-payments}
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

springdoc:
  packages-to-scan: io.github.wbdsjunior.taponphone.payments.controllers
