management:
  endpoint:
    health:
      probes:
        enabled: true
  zipkin:
    tracing:
      endpoint: ${SPRING_DISTRIBUTED_TRACING_ZIPKIN_ENDPONT:http://localhost:9411/api/v2/spans}

# resilience4j.timelimiter:
#   configs:
#     default:
#       cancelRunningFuture: true
#       timeoutDuration: 5s

server:
  error:
    include-binding-errors: on-param
    include-message: on-param
    whitelabel:
      enabled: false

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/taponphone-payments}
  docker:
    compose:
      file: docker-compose.development.yaml
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
     path: /api-docs/v3
  packages-to-scan: io.github.wbdsjunior.taponphone.payments.controllers
