logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
  zipkin:
    tracing:
      endpoint: ${SPRING_DISTRIBUTED_TRACING_ZIPKIN_ENDPONT:http://localhost:9411/api/v2/spans}

# resilience4j.timelimiter:
#   configs:
#     default:
#       cancelRunningFuture: true
#       timeoutDuration: 5s

server:
  error:
    include-binding-errors: on-param
    include-message: on-param
    whitelabel:
      enabled: false

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:postgres@localhost:5432/taponphone-authentications}
  docker:
    compose:
      file: docker-compose.development.yaml
  flyway:
    sql-migration-prefix: postgresql-v-
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
     path: /api-docs/v3
  packages-to-scan: io.github.wbdsjunior.taponphone.authentications.controllers
